name: Swift

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Swift
      uses: actions/setup-swift@v1
      with:
        swift-version: '5.3'

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
